// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using duedgusto.DataAccess;

#nullable disable

namespace duedgusto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221182434_RimozioneUltimoGiornoLavorativo")]
    partial class RimozioneUltimoGiornoLavorativo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RuoloMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RuoloId")
                        .HasColumnType("int");

                    b.HasKey("MenuId", "RuoloId");

                    b.HasIndex("RuoloId");

                    b.ToTable("RuoloMenu");
                });

            modelBuilder.Entity("duedgusto.Models.BusinessSettings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SettingsId"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClosingTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("18:00");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("EUR");

                    b.Property<string>("OpeningTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("09:00");

                    b.Property<string>("OperatingDays")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasDefaultValue("[true,true,true,true,true,false,false]");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Europe/Rome");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<decimal>("VatRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.22m);

                    b.HasKey("SettingsId");

                    b.ToTable("BusinessSettings", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.ChiusuraMensile", b =>
                {
                    b.Property<int>("ChiusuraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChiusuraId"));

                    b.Property<DateTime>("AggiornatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<int?>("ChiusaDa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ChiusaIl")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GiorniEsclusi")
                        .HasColumnType("longtext");

                    b.Property<int>("Mese")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("BOZZA");

                    b.HasKey("ChiusuraId");

                    b.HasIndex("ChiusaDa");

                    b.HasIndex("Stato");

                    b.HasIndex("Anno", "Mese")
                        .IsUnique();

                    b.ToTable("ChiusureMensili", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.ConteggioMoneta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DenominazioneMonetaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApertura")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Totale")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DenominazioneMonetaId");

                    b.HasIndex("RegistroCassaId");

                    b.ToTable("ConteggiMoneta", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.DenominazioneMoneta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdineVisualizzazione")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Valore")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("DenominazioniMoneta", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.DocumentoTrasporto", b =>
                {
                    b.Property<int>("DdtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DdtId"));

                    b.Property<DateTime>("AggiornatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataDdt")
                        .HasColumnType("date");

                    b.Property<int?>("FatturaId")
                        .HasColumnType("int");

                    b.Property<int>("FornitoreId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("NumeroDdt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DdtId");

                    b.HasIndex("DataDdt");

                    b.HasIndex("FatturaId");

                    b.HasIndex("FornitoreId", "NumeroDdt")
                        .IsUnique();

                    b.ToTable("DocumentiTrasporto", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.FatturaAcquisto", b =>
                {
                    b.Property<int>("FatturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FatturaId"));

                    b.Property<DateTime>("AggiornatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataFattura")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("date");

                    b.Property<int>("FornitoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Imponibile")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ImportoIva")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("NumeroFattura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DA_PAGARE");

                    b.Property<decimal?>("TotaleConIva")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FatturaId");

                    b.HasIndex("DataFattura");

                    b.HasIndex("Stato");

                    b.HasIndex("FornitoreId", "NumeroFattura")
                        .IsUnique();

                    b.ToTable("FattureAcquisto", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Fornitore", b =>
                {
                    b.Property<int>("FornitoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FornitoreId"));

                    b.Property<DateTime>("AggiornatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<bool>("Attivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Paese")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("IT");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FornitoreId");

                    b.HasIndex("Attivo");

                    b.HasIndex("PartitaIva")
                        .IsUnique()
                        .HasFilter("[PartitaIva] IS NOT NULL");

                    b.HasIndex("RagioneSociale");

                    b.ToTable("Fornitori", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.IncassoCassa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroCassaId");

                    b.ToTable("IncassiCassa", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icona")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MenuPadreId")
                        .HasColumnType("int");

                    b.Property<string>("NomeVista")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Percorso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PercorsoFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Posizione")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Visibile")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("MenuPadreId");

                    b.ToTable("Menus", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.PagamentoFornitore", b =>
                {
                    b.Property<int>("PagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PagamentoId"));

                    b.Property<DateTime>("AggiornatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<int?>("DdtId")
                        .HasColumnType("int");

                    b.Property<int?>("FatturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetodoPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("PagamentoId");

                    b.HasIndex("DataPagamento");

                    b.HasIndex("DdtId");

                    b.HasIndex("FatturaId");

                    b.ToTable("PagamentiFornitori", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.PagamentoMensileFornitori", b =>
                {
                    b.Property<int>("ChiusuraId")
                        .HasColumnType("int");

                    b.Property<int>("PagamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("InclusoInChiusura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("ChiusuraId", "PagamentoId");

                    b.HasIndex("ChiusuraId");

                    b.HasIndex("PagamentoId");

                    b.ToTable("PagamentiMensiliFornitori", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnitOfMeasure")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pz");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("ProductId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AggiornatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<decimal>("ContanteAtteso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ContanteNetto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<decimal>("Differenza")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ImportoIva")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("IncassiElettronici")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("IncassiFattura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("IncassoContanteTracciato")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("SpeseFornitori")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SpeseGiornaliere")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DRAFT");

                    b.Property<decimal>("TotaleApertura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotaleChiusura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotaleVendite")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("VenditeContanti")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .IsUnique();

                    b.HasIndex("UtenteId");

                    b.ToTable("RegistriCassa", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassaMensile", b =>
                {
                    b.Property<int>("ChiusuraId")
                        .HasColumnType("int");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<bool>("Incluso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("ChiusuraId", "RegistroId");

                    b.HasIndex("ChiusuraId");

                    b.HasIndex("RegistroId");

                    b.ToTable("RegistriCassaMensili", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Ruolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ruoli", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("SaleId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RegistroCassaId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Sales", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.SpesaCassa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroCassaId");

                    b.ToTable("SpeseCassa", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.SpesaMensile", b =>
                {
                    b.Property<int>("SpesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpesaId"));

                    b.Property<DateTime>("AggiornatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ChiusuraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("int");

                    b.HasKey("SpesaId");

                    b.HasIndex("Categoria");

                    b.HasIndex("ChiusuraId");

                    b.HasIndex("PagamentoId");

                    b.ToTable("SpeseMensili", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.SpesaMensileLibera", b =>
                {
                    b.Property<int>("SpesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpesaId"));

                    b.Property<DateTime>("AggiornatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ChiusuraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatoIl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SpesaId");

                    b.HasIndex("Categoria");

                    b.HasIndex("ChiusuraId");

                    b.ToTable("SpeseMensiliLibere", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .HasColumnType("longtext");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Disabilitato")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RuoloId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("ScadenzaTokenAggiornamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenAggiornamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RuoloId");

                    b.ToTable("Utenti", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RuoloMenu", b =>
                {
                    b.HasOne("duedgusto.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.Ruolo", null)
                        .WithMany()
                        .HasForeignKey("RuoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("duedgusto.Models.ChiusuraMensile", b =>
                {
                    b.HasOne("duedgusto.Models.Utente", "ChiusaDaUtente")
                        .WithMany()
                        .HasForeignKey("ChiusaDa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChiusaDaUtente");
                });

            modelBuilder.Entity("duedgusto.Models.ConteggioMoneta", b =>
                {
                    b.HasOne("duedgusto.Models.DenominazioneMoneta", "Denominazione")
                        .WithMany("ConteggiMoneta")
                        .HasForeignKey("DenominazioneMonetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany("ConteggiMoneta")
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denominazione");

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.DocumentoTrasporto", b =>
                {
                    b.HasOne("duedgusto.Models.FatturaAcquisto", "Fattura")
                        .WithMany("DocumentiTrasporto")
                        .HasForeignKey("FatturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("duedgusto.Models.Fornitore", "Fornitore")
                        .WithMany("DocumentiTrasporto")
                        .HasForeignKey("FornitoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fattura");

                    b.Navigation("Fornitore");
                });

            modelBuilder.Entity("duedgusto.Models.FatturaAcquisto", b =>
                {
                    b.HasOne("duedgusto.Models.Fornitore", "Fornitore")
                        .WithMany("FattureAcquisto")
                        .HasForeignKey("FornitoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornitore");
                });

            modelBuilder.Entity("duedgusto.Models.IncassoCassa", b =>
                {
                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany("IncassiCassa")
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.Menu", b =>
                {
                    b.HasOne("duedgusto.Models.Menu", "MenuPadre")
                        .WithMany("Figli")
                        .HasForeignKey("MenuPadreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MenuPadre");
                });

            modelBuilder.Entity("duedgusto.Models.PagamentoFornitore", b =>
                {
                    b.HasOne("duedgusto.Models.DocumentoTrasporto", "Ddt")
                        .WithMany("Pagamenti")
                        .HasForeignKey("DdtId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("duedgusto.Models.FatturaAcquisto", "Fattura")
                        .WithMany("Pagamenti")
                        .HasForeignKey("FatturaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ddt");

                    b.Navigation("Fattura");
                });

            modelBuilder.Entity("duedgusto.Models.PagamentoMensileFornitori", b =>
                {
                    b.HasOne("duedgusto.Models.ChiusuraMensile", "Chiusura")
                        .WithMany("PagamentiInclusi")
                        .HasForeignKey("ChiusuraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.PagamentoFornitore", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chiusura");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassa", b =>
                {
                    b.HasOne("duedgusto.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassaMensile", b =>
                {
                    b.HasOne("duedgusto.Models.ChiusuraMensile", "Chiusura")
                        .WithMany("RegistriInclusi")
                        .HasForeignKey("ChiusuraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.RegistroCassa", "Registro")
                        .WithMany()
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chiusura");

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("duedgusto.Models.Sale", b =>
                {
                    b.HasOne("duedgusto.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany()
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.SpesaCassa", b =>
                {
                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany("SpeseCassa")
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.SpesaMensile", b =>
                {
                    b.HasOne("duedgusto.Models.ChiusuraMensile", "Chiusura")
                        .WithMany()
                        .HasForeignKey("ChiusuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.PagamentoFornitore", "Pagamento")
                        .WithMany("SpeseMensili")
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chiusura");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("duedgusto.Models.SpesaMensileLibera", b =>
                {
                    b.HasOne("duedgusto.Models.ChiusuraMensile", "Chiusura")
                        .WithMany("SpeseLibere")
                        .HasForeignKey("ChiusuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chiusura");
                });

            modelBuilder.Entity("duedgusto.Models.Utente", b =>
                {
                    b.HasOne("duedgusto.Models.Ruolo", "Ruolo")
                        .WithMany("Utenti")
                        .HasForeignKey("RuoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruolo");
                });

            modelBuilder.Entity("duedgusto.Models.ChiusuraMensile", b =>
                {
                    b.Navigation("PagamentiInclusi");

                    b.Navigation("RegistriInclusi");

                    b.Navigation("SpeseLibere");
                });

            modelBuilder.Entity("duedgusto.Models.DenominazioneMoneta", b =>
                {
                    b.Navigation("ConteggiMoneta");
                });

            modelBuilder.Entity("duedgusto.Models.DocumentoTrasporto", b =>
                {
                    b.Navigation("Pagamenti");
                });

            modelBuilder.Entity("duedgusto.Models.FatturaAcquisto", b =>
                {
                    b.Navigation("DocumentiTrasporto");

                    b.Navigation("Pagamenti");
                });

            modelBuilder.Entity("duedgusto.Models.Fornitore", b =>
                {
                    b.Navigation("DocumentiTrasporto");

                    b.Navigation("FattureAcquisto");
                });

            modelBuilder.Entity("duedgusto.Models.Menu", b =>
                {
                    b.Navigation("Figli");
                });

            modelBuilder.Entity("duedgusto.Models.PagamentoFornitore", b =>
                {
                    b.Navigation("SpeseMensili");
                });

            modelBuilder.Entity("duedgusto.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassa", b =>
                {
                    b.Navigation("ConteggiMoneta");

                    b.Navigation("IncassiCassa");

                    b.Navigation("SpeseCassa");
                });

            modelBuilder.Entity("duedgusto.Models.Ruolo", b =>
                {
                    b.Navigation("Utenti");
                });
#pragma warning restore 612, 618
        }
    }
}
