// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using duedgusto.DataAccess;

#nullable disable

namespace duedgusto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829070649_RiordinaIndiceOrdiniStato")]
    partial class RiordinaIndiceOrdiniStato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RuoloMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RuoloId")
                        .HasColumnType("int");

                    b.HasKey("MenuId", "RuoloId");

                    b.HasIndex("RuoloId");

                    b.ToTable("RuoloMenu");
                });

            modelBuilder.Entity("duedgusto.Models.BusinessSettings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SettingsId"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClosingTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("18:00");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("EUR");

                    b.Property<decimal>("GiornaleImportoFeriale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(3.20m);

                    b.Property<decimal>("GiornaleImportoSabato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(5.00m);

                    b.Property<string>("OpeningTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("09:00");

                    b.Property<string>("OperatingDays")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasDefaultValue("[true,true,true,true,true,false,false]");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Europe/Rome");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<decimal>("VatRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.10m);

                    b.HasKey("SettingsId");

                    b.ToTable("BusinessSettings", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.ChiusuraMensile", b =>
                {
                    b.Property<int>("ChiusuraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChiusuraId"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<int?>("ChiusaDa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ChiusaIl")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GiorniEsclusi")
                        .HasColumnType("longtext");

                    b.Property<int>("Mese")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("BOZZA");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("ChiusuraId");

                    b.HasIndex("ChiusaDa");

                    b.HasIndex("Stato");

                    b.HasIndex("Anno", "Mese")
                        .IsUnique();

                    b.ToTable("ChiusureMensili", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.ConteggioMoneta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DenominazioneMonetaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApertura")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Totale")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DenominazioneMonetaId");

                    b.HasIndex("RegistroCassaId");

                    b.ToTable("ConteggiMoneta", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.DenominazioneMoneta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdineVisualizzazione")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Valore")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("DenominazioniMoneta", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.DocumentoTrasporto", b =>
                {
                    b.Property<int>("DdtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DdtId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataDdt")
                        .HasColumnType("date");

                    b.Property<int?>("FatturaId")
                        .HasColumnType("int");

                    b.Property<int>("FornitoreId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("NumeroDdt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("DdtId");

                    b.HasIndex("DataDdt");

                    b.HasIndex("FatturaId");

                    b.HasIndex("FornitoreId", "NumeroDdt")
                        .IsUnique();

                    b.ToTable("DocumentiTrasporto", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.FatturaAcquisto", b =>
                {
                    b.Property<int>("FatturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FatturaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataFattura")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("date");

                    b.Property<int>("FornitoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Imponibile")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ImportoIva")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IvaCalcolata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("NumeroFattura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DA_PAGARE");

                    b.Property<decimal?>("TotaleConIva")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("FatturaId");

                    b.HasIndex("DataFattura");

                    b.HasIndex("Stato");

                    b.HasIndex("FornitoreId", "NumeroFattura")
                        .IsUnique();

                    b.ToTable("FattureAcquisto", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Fornitore", b =>
                {
                    b.Property<int>("FornitoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FornitoreId"));

                    b.Property<decimal?>("AliquotaIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Attivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Paese")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("IT");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RagioneSociale2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("FornitoreId");

                    b.HasIndex("Attivo");

                    b.HasIndex("PartitaIva")
                        .IsUnique()
                        .HasFilter("[PartitaIva] IS NOT NULL");

                    b.HasIndex("RagioneSociale");

                    b.ToTable("Fornitori", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.GiornoNonLavorativo", b =>
                {
                    b.Property<int>("GiornoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GiornoId"));

                    b.Property<string>("CodiceMotivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("FESTIVITA_NAZIONALE");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Ricorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("SettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("GiornoId");

                    b.HasIndex("SettingsId", "Data")
                        .IsUnique();

                    b.ToTable("GiorniNonLavorativi", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.ImpostazioniVetrina", b =>
                {
                    b.Property<int>("ImpostazioniVetrinaId")
                        .HasColumnType("int");

                    b.Property<string>("AperitivoCategorie")
                        .HasColumnType("text");

                    b.Property<string>("AperitivoPunti")
                        .HasColumnType("text");

                    b.Property<string>("AperitivoTesto")
                        .HasColumnType("text");

                    b.Property<string>("AperitivoTitolo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimVetrina")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ImmagineEroeAperitivoId")
                        .HasColumnType("int");

                    b.Property<int?>("ImmagineEroeHomeId")
                        .HasColumnType("int");

                    b.Property<int?>("ImmagineOgId")
                        .HasColumnType("int");

                    b.Property<int?>("ImmagineRitrattoLocaleId")
                        .HasColumnType("int");

                    b.Property<string>("InsegnaPubblica")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("Latitudine")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitudine")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("MetaDescrizioneDefault")
                        .HasColumnType("text");

                    b.Property<string>("MetaTitoloDefault")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("NumeroRecensioniGoogle")
                        .HasColumnType("int");

                    b.Property<string>("OraInizioTemaSera")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("18:00");

                    b.Property<string>("Paese")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("IT");

                    b.Property<bool>("PrenotazioniAttive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PrenotazioniCopertiMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<int>("PrenotazioniPreavvisoOre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("PunteggioGoogle")
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("StoriaTesto")
                        .HasColumnType("text");

                    b.Property<string>("StoriaTitolo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TurnstileSiteKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<string>("UrlFacebook")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UrlInstagram")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UrlProfiloGoogle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ImpostazioniVetrinaId");

                    b.HasIndex("ImmagineEroeAperitivoId");

                    b.HasIndex("ImmagineEroeHomeId");

                    b.HasIndex("ImmagineOgId");

                    b.HasIndex("ImmagineRitrattoLocaleId");

                    b.ToTable("ImpostazioniVetrina", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImpostazioniVetrina_Singleton", "`ImpostazioniVetrinaId` = 1");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.MediaAsset", b =>
                {
                    b.Property<int>("MediaAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MediaAssetId"));

                    b.Property<int>("Altezza")
                        .HasColumnType("int");

                    b.Property<long>("ByteTotali")
                        .HasColumnType("bigint");

                    b.Property<string>("Cartella")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("generale");

                    b.Property<string>("Chiave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Didascalia")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Focale")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Larghezza")
                        .HasColumnType("int");

                    b.Property<string>("LarghezzeDisponibili")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeOriginale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Ordinamento")
                        .HasColumnType("int");

                    b.Property<string>("Placeholder")
                        .HasColumnType("text");

                    b.Property<bool>("Pubblicato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("TestoAlternativo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("MediaAssetId");

                    b.HasIndex("Chiave")
                        .IsUnique();

                    b.HasIndex("Cartella", "Ordinamento");

                    b.ToTable("MediaAssets", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icona")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MenuPadreId")
                        .HasColumnType("int");

                    b.Property<string>("NomeVista")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Percorso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PercorsoFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Posizione")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Visibile")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("MenuPadreId");

                    b.ToTable("Menus", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Ordine", b =>
                {
                    b.Property<int>("OrdineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrdineId"));

                    b.Property<int?>("AnnullatoDa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnnullatoIl")
                        .HasColumnType("datetime");

                    b.Property<int?>("ApertoDa")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApertoIl")
                        .HasColumnType("datetime");

                    b.Property<int?>("ChiusoDa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ChiusoIl")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ContanteRicevuto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MetodoPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MotivoAnnullamento")
                        .HasColumnType("text");

                    b.Property<string>("MotivoStorno")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("OrdinePadreId")
                        .HasColumnType("int");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.Property<string>("Stato")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("APERTO");

                    b.Property<int?>("StornatoDa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StornatoIl")
                        .HasColumnType("datetime");

                    b.Property<string>("SuffissoSplit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("");

                    b.Property<decimal>("TotaleOrdine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("OrdineId");

                    b.HasIndex("OrdinePadreId");

                    b.HasIndex("Stato", "RegistroCassaId");

                    b.HasIndex("RegistroCassaId", "Numero", "SuffissoSplit")
                        .IsUnique();

                    b.ToTable("Ordini", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.PagamentoFornitore", b =>
                {
                    b.Property<int>("PagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PagamentoId"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<int?>("DdtId")
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<int?>("FatturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetodoPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("RegistroCassaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("PagamentoId");

                    b.HasIndex("DataPagamento");

                    b.HasIndex("DdtId");

                    b.HasIndex("FatturaId");

                    b.HasIndex("RegistroCassaId");

                    b.ToTable("PagamentiFornitori", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.PeriodoProgrammazione", b =>
                {
                    b.Property<int>("PeriodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PeriodoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DataFine")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInizio")
                        .HasColumnType("date");

                    b.Property<string>("GiorniOperativi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasDefaultValue("[true,true,true,true,true,false,false]");

                    b.Property<TimeOnly>("OrarioApertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(9, 0, 0));

                    b.Property<TimeOnly>("OrarioChiusura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(18, 0, 0));

                    b.Property<int>("SettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("PeriodoId");

                    b.HasIndex("SettingsId", "DataInizio");

                    b.ToTable("PeriodiProgrammazione", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Prodotto", b =>
                {
                    b.Property<int>("ProdottoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProdottoId"));

                    b.Property<decimal>("AliquotaIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(22.00m);

                    b.Property<string>("Allergeni")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Attivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoriaVetrina")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Consigliato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<string>("DescrizioneVetrina")
                        .HasColumnType("text");

                    b.Property<int?>("ImmagineId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("InLavagnaDal")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeVetrina")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Novita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("OrdinamentoVetrina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrezzoVetrina")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnitaDiMisura")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pz");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<bool>("VisibileSulSito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("ProdottoId");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.HasIndex("ImmagineId");

                    b.HasIndex("InLavagnaDal")
                        .HasDatabaseName("IX_Prodotti_InLavagnaDal");

                    b.HasIndex("VisibileSulSito");

                    b.ToTable("Prodotti", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.RecensioneVetrina", b =>
                {
                    b.Property<int>("RecensioneVetrinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecensioneVetrinaId"));

                    b.Property<string>("Autore")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Fonte")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Ordinamento")
                        .HasColumnType("int");

                    b.Property<bool>("Pubblicata")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Punteggio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("RecensioneVetrinaId");

                    b.HasIndex("Pubblicata", "Ordinamento")
                        .HasDatabaseName("IX_RecensioniVetrina_Pubblicata_Ordinamento");

                    b.ToTable("RecensioniVetrina", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecensioniVetrina_Punteggio", "`Punteggio` BETWEEN 1 AND 5");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ContanteNetto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<decimal>("Ecc")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ImportoIva")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("IncassiElettronici")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("IncassiFattura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("IncassoContanteTracciato")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("Resto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RestoFornitore")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SpeseFornitori")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SpeseGiornaliere")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DRAFT");

                    b.Property<decimal>("TotaleApertura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotaleChiusura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotaleVendite")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("VenditeContanti")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .IsUnique();

                    b.HasIndex("UtenteId");

                    b.ToTable("RegistriCassa", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassaIva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Imponibile")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Imposta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.Property<bool>("Stimato")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroCassaId");

                    b.HasIndex("RegistroCassaId", "Aliquota", "Stimato")
                        .IsUnique();

                    b.ToTable("RegistriCassaIva", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassaMensile", b =>
                {
                    b.Property<int>("ChiusuraId")
                        .HasColumnType("int");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<bool>("Incluso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("ChiusuraId", "RegistroId");

                    b.HasIndex("ChiusuraId");

                    b.HasIndex("RegistroId");

                    b.ToTable("RegistriCassaMensili", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.RigaOrdine", b =>
                {
                    b.Property<int>("RigaOrdineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RigaOrdineId"));

                    b.Property<decimal>("AliquotaIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(10.00m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoTotale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantita")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("RigaOrdineId");

                    b.HasIndex("OrdineId");

                    b.HasIndex("ProdottoId");

                    b.ToTable("RigheOrdine", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Ruolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Amministratore")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ruoli", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.SpesaCassa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Altro");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroCassaId");

                    b.ToTable("SpeseCassa", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .HasColumnType("longtext");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Disabilitato")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreferenzaDragModale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("free");

                    b.Property<int>("RuoloId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("ScadenzaTokenAggiornamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenAggiornamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RuoloId");

                    b.ToTable("Utenti", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("duedgusto.Models.Vendita", b =>
                {
                    b.Property<int>("VenditaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VenditaId"));

                    b.Property<decimal>("AliquotaIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(22.00m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Imponibile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ImportoIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("CONTANTE_NON_TRACCIATO");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoTotale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantita")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RegistroCassaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("VenditaId");

                    b.HasIndex("DataOra");

                    b.HasIndex("OrdineId");

                    b.HasIndex("ProdottoId");

                    b.HasIndex("RegistroCassaId");

                    b.ToTable("Vendite", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RuoloMenu", b =>
                {
                    b.HasOne("duedgusto.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.Ruolo", null)
                        .WithMany()
                        .HasForeignKey("RuoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("duedgusto.Models.ChiusuraMensile", b =>
                {
                    b.HasOne("duedgusto.Models.Utente", "ChiusaDaUtente")
                        .WithMany()
                        .HasForeignKey("ChiusaDa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChiusaDaUtente");
                });

            modelBuilder.Entity("duedgusto.Models.ConteggioMoneta", b =>
                {
                    b.HasOne("duedgusto.Models.DenominazioneMoneta", "Denominazione")
                        .WithMany("ConteggiMoneta")
                        .HasForeignKey("DenominazioneMonetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany("ConteggiMoneta")
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denominazione");

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.DocumentoTrasporto", b =>
                {
                    b.HasOne("duedgusto.Models.FatturaAcquisto", "Fattura")
                        .WithMany("DocumentiTrasporto")
                        .HasForeignKey("FatturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("duedgusto.Models.Fornitore", "Fornitore")
                        .WithMany("DocumentiTrasporto")
                        .HasForeignKey("FornitoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fattura");

                    b.Navigation("Fornitore");
                });

            modelBuilder.Entity("duedgusto.Models.FatturaAcquisto", b =>
                {
                    b.HasOne("duedgusto.Models.Fornitore", "Fornitore")
                        .WithMany("FattureAcquisto")
                        .HasForeignKey("FornitoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornitore");
                });

            modelBuilder.Entity("duedgusto.Models.GiornoNonLavorativo", b =>
                {
                    b.HasOne("duedgusto.Models.BusinessSettings", "Settings")
                        .WithMany("GiorniNonLavorativi")
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("duedgusto.Models.ImpostazioniVetrina", b =>
                {
                    b.HasOne("duedgusto.Models.MediaAsset", "ImmagineEroeAperitivo")
                        .WithMany()
                        .HasForeignKey("ImmagineEroeAperitivoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("duedgusto.Models.MediaAsset", "ImmagineEroeHome")
                        .WithMany()
                        .HasForeignKey("ImmagineEroeHomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("duedgusto.Models.MediaAsset", "ImmagineOg")
                        .WithMany()
                        .HasForeignKey("ImmagineOgId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("duedgusto.Models.MediaAsset", "ImmagineRitrattoLocale")
                        .WithMany()
                        .HasForeignKey("ImmagineRitrattoLocaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ImmagineEroeAperitivo");

                    b.Navigation("ImmagineEroeHome");

                    b.Navigation("ImmagineOg");

                    b.Navigation("ImmagineRitrattoLocale");
                });

            modelBuilder.Entity("duedgusto.Models.Menu", b =>
                {
                    b.HasOne("duedgusto.Models.Menu", "MenuPadre")
                        .WithMany("Figli")
                        .HasForeignKey("MenuPadreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MenuPadre");
                });

            modelBuilder.Entity("duedgusto.Models.Ordine", b =>
                {
                    b.HasOne("duedgusto.Models.Ordine", "OrdinePadre")
                        .WithMany("Figli")
                        .HasForeignKey("OrdinePadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany()
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdinePadre");

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.PagamentoFornitore", b =>
                {
                    b.HasOne("duedgusto.Models.DocumentoTrasporto", "Ddt")
                        .WithMany("Pagamenti")
                        .HasForeignKey("DdtId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("duedgusto.Models.FatturaAcquisto", "Fattura")
                        .WithMany("Pagamenti")
                        .HasForeignKey("FatturaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany("PagamentiFornitori")
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ddt");

                    b.Navigation("Fattura");

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.PeriodoProgrammazione", b =>
                {
                    b.HasOne("duedgusto.Models.BusinessSettings", "Settings")
                        .WithMany("Periodi")
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("duedgusto.Models.Prodotto", b =>
                {
                    b.HasOne("duedgusto.Models.MediaAsset", "Immagine")
                        .WithMany("Prodotti")
                        .HasForeignKey("ImmagineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Immagine");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassa", b =>
                {
                    b.HasOne("duedgusto.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassaIva", b =>
                {
                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany("BreakdownIva")
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassaMensile", b =>
                {
                    b.HasOne("duedgusto.Models.ChiusuraMensile", "Chiusura")
                        .WithMany("RegistriInclusi")
                        .HasForeignKey("ChiusuraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.RegistroCassa", "Registro")
                        .WithMany()
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chiusura");

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("duedgusto.Models.RigaOrdine", b =>
                {
                    b.HasOne("duedgusto.Models.Ordine", "Ordine")
                        .WithMany("Righe")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.Prodotto", "Prodotto")
                        .WithMany()
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("duedgusto.Models.SpesaCassa", b =>
                {
                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany("SpeseCassa")
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.Utente", b =>
                {
                    b.HasOne("duedgusto.Models.Ruolo", "Ruolo")
                        .WithMany("Utenti")
                        .HasForeignKey("RuoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruolo");
                });

            modelBuilder.Entity("duedgusto.Models.Vendita", b =>
                {
                    b.HasOne("duedgusto.Models.Ordine", "Ordine")
                        .WithMany("Vendite")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("duedgusto.Models.Prodotto", "Prodotto")
                        .WithMany("Vendite")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("duedgusto.Models.RegistroCassa", "RegistroCassa")
                        .WithMany()
                        .HasForeignKey("RegistroCassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("Prodotto");

                    b.Navigation("RegistroCassa");
                });

            modelBuilder.Entity("duedgusto.Models.BusinessSettings", b =>
                {
                    b.Navigation("GiorniNonLavorativi");

                    b.Navigation("Periodi");
                });

            modelBuilder.Entity("duedgusto.Models.ChiusuraMensile", b =>
                {
                    b.Navigation("RegistriInclusi");
                });

            modelBuilder.Entity("duedgusto.Models.DenominazioneMoneta", b =>
                {
                    b.Navigation("ConteggiMoneta");
                });

            modelBuilder.Entity("duedgusto.Models.DocumentoTrasporto", b =>
                {
                    b.Navigation("Pagamenti");
                });

            modelBuilder.Entity("duedgusto.Models.FatturaAcquisto", b =>
                {
                    b.Navigation("DocumentiTrasporto");

                    b.Navigation("Pagamenti");
                });

            modelBuilder.Entity("duedgusto.Models.Fornitore", b =>
                {
                    b.Navigation("DocumentiTrasporto");

                    b.Navigation("FattureAcquisto");
                });

            modelBuilder.Entity("duedgusto.Models.MediaAsset", b =>
                {
                    b.Navigation("Prodotti");
                });

            modelBuilder.Entity("duedgusto.Models.Menu", b =>
                {
                    b.Navigation("Figli");
                });

            modelBuilder.Entity("duedgusto.Models.Ordine", b =>
                {
                    b.Navigation("Figli");

                    b.Navigation("Righe");

                    b.Navigation("Vendite");
                });

            modelBuilder.Entity("duedgusto.Models.Prodotto", b =>
                {
                    b.Navigation("Vendite");
                });

            modelBuilder.Entity("duedgusto.Models.RegistroCassa", b =>
                {
                    b.Navigation("BreakdownIva");

                    b.Navigation("ConteggiMoneta");

                    b.Navigation("PagamentiFornitori");

                    b.Navigation("SpeseCassa");
                });

            modelBuilder.Entity("duedgusto.Models.Ruolo", b =>
                {
                    b.Navigation("Utenti");
                });
#pragma warning restore 612, 618
        }
    }
}
