import {
  LayoutDashboard,
  Users,
  Wrench,
  List,
  Settings,
  ShoppingCart,
  CalendarRange,
  CalendarDays,
  Pencil,
  Warehouse,
  UserRound,
  Receipt,
  Truck,
  ClipboardList,
  CalendarCheck,
  FilePenLine,
  FileEdit,
  PackageSearch,
  UserCog,
  FileText,
  Menu,
  Shield,
  BookOpen,
  BookText,
  Globe,
  Images,
  ShoppingBag,
  Store,
  type LucideIcon,
} from "lucide-react";

export const iconMapping: Record<string, LucideIcon> = {
  LayoutDashboard,
  Users,
  Wrench,
  List,
  Settings,
  ShoppingCart,
  CalendarRange,
  CalendarDays,
  Pencil,
  Warehouse,
  UserRound,
  Receipt,
  Truck,
  ClipboardList,
  CalendarCheck,
  FilePenLine,
  FileEdit,
  PackageSearch,
  UserCog,
  FileText,
  Menu,
  Shield,
  BookOpen,
  BookText,
  Globe,
  Images,
  ShoppingBag,
  // ⚠️ Non si riusa `Settings`: è già la sezione Impostazioni della cassa, e nella barra di
  // navigazione le due voci sarebbero indistinguibili — proprio le due che non vanno confuse.
  Store,
};
