import {
  LayoutDashboard,
  Users,
  Wrench,
  List,
  Settings,
  ShoppingCart,
  CalendarRange,
  CalendarDays,
  Pencil,
  Warehouse,
  UserRound,
  Receipt,
  Truck,
  ClipboardList,
  CalendarCheck,
  FilePenLine,
  FileEdit,
  PackageSearch,
  UserCog,
  FileText,
  Menu,
  Shield,
  BookOpen,
  BookText,
  Globe,
  Images,
  ShoppingBag,
  Store,
  Star,
  type LucideIcon,
} from "lucide-react";

export const iconMapping: Record<string, LucideIcon> = {
  LayoutDashboard,
  Users,
  Wrench,
  List,
  Settings,
  ShoppingCart,
  CalendarRange,
  CalendarDays,
  Pencil,
  Warehouse,
  UserRound,
  Receipt,
  Truck,
  ClipboardList,
  CalendarCheck,
  FilePenLine,
  FileEdit,
  PackageSearch,
  UserCog,
  FileText,
  Menu,
  Shield,
  BookOpen,
  BookText,
  Globe,
  Images,
  ShoppingBag,
  // ⚠️ Non si riusa `Settings`: è già la sezione Impostazioni della cassa, e nella barra di
  // navigazione le due voci sarebbero indistinguibili — proprio le due che non vanno confuse.
  Store,
  // 🔴 Un'icona che manca qui non dà errore: la voce di menu compare **senza icona**, e la
  //    cosa si nota solo guardando la barra. Il seed la nomina come stringa, quindi le due
  //    liste vanno tenute allineate a mano — è il prezzo di avere le voci a database.
  Star,
};
